name: Deploy to PROD

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Docker is available
        run: |
          docker version
          docker info

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull & run container
        run: |
          set IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/devops-java-app:latest
          echo Deploy image: %IMAGE%
          docker pull %IMAGE%
          docker rm -f devops-java-app 2>nul
          docker run -d --name devops-java-app -p 8080:8080 %IMAGE%
          powershell -NoProfile -ExecutionPolicy Bypass -Command "Start-Sleep -Seconds 5; (Invoke-WebRequest -UseBasicParsing http://localhost:8080).StatusCode | Out-Host"

      - name: Label PR as PROD (if triggered by PR merge)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: PROD