name: Create GitHub Release

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: echo "VERSION=$(cat version)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release with changelog
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: Release v${{ steps.version.outputs.VERSION }}
          body_path: ./changelog.md
          files: ./changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}