name: Security Audit

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  antivirus:
    name: Antivirus Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ClamAV and run scan
        run: |
          sudo apt-get update
          sudo apt-get install -y clamav
          clamscan -r .

  dependency-check:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'devops-java-pipeline'
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 7
            --scan target/*.jar
            --enableRetired

  spotbugs:
    name: SpotBugs Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn compile -DskipTests
      - name: Run SpotBugs
        run: mvn spotbugs:check

  checkstyle:
    name: CheckStyle Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run CheckStyle
        run: mvn checkstyle:check